### ISSUE TITLE
Importing task stopping after around task step 2200 without any errors

### ISSUE THREAD

**Issue by bkmorse** [boboldehampsink/import#107]
Craft Pro 2.5.2767
Import 0.8.28

I have been breaking up utf-8 csv files up into chunks of 8000 records and it does not complete the entire import.

I've checked the phperrors.log craft file, as well as the error logs on the server.

Initially I was not able to run the import on a csv with 8000+ records due to memory being exhausted so I added ini_set('memory_limit','-1'); (not smart but needed to get this imported) to line 755 of ImportService.php where it opens the csv file uploaded and gets the lines to import, which allowed me to import it.

I checked the import log table and no logs stick out as to why it would stop running. I checked the max_execution_time, it is set at 30, the server is set to devmode and it would log if it was a max_execution_time.

Have you come across this with large csv files? Its a 4.9mb csv file.

**Comment by boboldehampsink** [comment]
This shouldn't be a problem, but it could still be a memory limit thing. It probably is.

**Comment by bkmorse** [comment]
I divided the file into chunks of 1200 rows for each csv and that worked. It was odd that it did not time out and give some memory warning.
