### ISSUE TITLE
Categories & assets not importing

### ISSUE THREAD

**Issue by theswebsite** [boboldehampsink/import#119]
I can't seem to get any categories or assets to import correctly. I used the Export plugin to export data and change a few things then re-import. Everything is successful until I go to the entry in Craft and see that no categories or assets have been mapped to the entry.

Many thanks

**Comment by boboldehampsink** [comment]
This seems to be a duplicate of #107

**Comment by muerl** [comment]
FYI this is a duplicate of #106 not #107
