### ISSUE TITLE
Import into Table Fields?

### ISSUE THREAD

**Issue by jonlongnecker** [boboldehampsink/import#125]
Is is possible to import data from a Matrix field in ExpressionEngine into a Table field in Craft? I'm not seeing a way to map any data to the individual rows in the table field.

thanks!

Jonathan

**Comment by boboldehampsink** [comment]
Use the [`modifyImportRow`](https://github.com/boboldehampsink/import#modifyimportrow) hook

**Comment by jonlongnecker** [comment]
Ah - I guess I was hoping for something a little more automated :)

thanks,

Jonathan

**Comment by ChaseGiunta** [comment]
@boboldehampsink is there a example of importing data into a simple table or simple matrix field? I'm struggling with figuring out where I might be going wrong (csv syntax? `modifyImportRow` syntax? something else?). A very basic example would be extremely helpful!

**Comment by smockensturm** [comment]
Hey @jonlongnecker @ChaseGiunta 

We're trying to do exactly this. Follow along [here](http://craftcms.stackexchange.com/questions/16263/why-wont-hampsinks-import-plugin-accept-this-json-string) and help us get it working. :)

**Comment by ChaseGiunta** [comment]
Steve, if you have it figured it all out, would you mind posting the full snippet? A screenshot of your table field, before or after import, might also be helpful. This is one of those things I need explained to me like a 2nd grader ;)

**Comment by smockensturm** [comment]
Sure thing. Give me a few.

In the meantime, brush up on writing a simple plugin? The Getting Started section here will... get you started.

https://craftcms.com/docs/plugins/introduction

**Comment by ChaseGiunta** [comment]
Thanks! Luckily, I got the plugin figured out. I assume I'm placing this in a BusinessLogic plugin in my `init`... It's the whole mapping fields -> columns, dealing with php associative arrays, and JSON syntax that's driving me mad.

**Comment by steverowling** [comment]
Hi Chase, I answered Steve's SE question. [I've now expanded my answer](http://craftcms.stackexchange.com/a/16265/153) to show the full `modifyImportRow` function you'll need to add to your main plugin class to make this work. Hope this helps!

**Comment by ChaseGiunta** [comment]
So I have a gist going of some basic examples I'd like to improve upon for folks searching like I was. Right now it's showing how to import (replacing data) or tables & Super Tables, and the start of a Matrix example (I could use some help!). I'm by no means a PHP expert so if they could be improved in any way, please don't hesitate to contribute.
https://gist.github.com/ChaseGiunta/da7aec29dfe6679d1de18e8b308f7d9e

**Comment by boboldehampsink** [comment]
Awesome, thanks!
