### ISSUE TITLE
Import stuck on updating uri & slugs

### ISSUE THREAD

**Issue by subratom** [boboldehampsink/import#126]
I am replacing category data and now for past 4+ hours it's stuck on updating slugs & uri message. I have about 2400 entries and I see in tasks table about 880 entries in pending state. Not sure if it is doing anything at this point

**Comment by boboldehampsink** [comment]
It probably ran out of memory. Try again, and if it keeps failing increase your memory.

**Comment by boboldehampsink** [comment]
Did this work for you?
