### ISSUE TITLE
Import task never begins

### ISSUE THREAD

**Issue by ChaseGiunta** [boboldehampsink/import#127]
Trying to import user data...
My CSV (for testing) is as simple as this
```
email, username, highSchool
10920646@live.mercer.edu, 10920646@live.mercer.edu, PAULDING HIGH SCHOOL
112174.ch@gmail.com, 112174.ch@gmail.com, ROYAL CITY HIGH SCHOOL
14doughjerj@washk12.org, 14doughjerj@washk12.org, ENTERPRISE
15jvogel96@gmail.com, 15jvogel96@gmail.com, RIVERSIDE
```

Using emailAsUsername so including username data as a precaution, recommended on another issue. Everything seems to detect mapping correctly.
![image](https://cloud.githubusercontent.com/assets/1377169/17079211/ae679fe8-50ce-11e6-99ba-87aa822bf89d.png)

Upon starting the import, nothing happens. A task is created, but never starts. It will remain on "pending" indefinitely. No other tasks exist, so no stuck tasks preventing. There is nothing showing up in Craft logs (no log files for import plugin exist).

Craft 2.6.2797
Import 0.8.32

**Comment by boboldehampsink** [comment]
Looks like a Craft issue to me. Have you set `runPendingTasksAutomatically` to `false`?

**Comment by ChaseGiunta** [comment]
I have not. Other tasks begin & run in entirety just fine.

**Comment by boboldehampsink** [comment]
As long as it's pending, the import hasn't even started. You should contact Craft support initially.

**Comment by ChaseGiunta** [comment]
I tracked this down to being an issue with Laravel Valet, which I'm using for my development environment and some incompatibility with how the tasks kick off. Not quite sure _what_ exactly is the difference is with Valet, or why some tasks work fine and others don't, but running the site through MAMP resolves my issue with Import.

**Comment by ChaseGiunta** [comment]
Just an update: I've resolved the issue through a couple added lines in the plugin explained here: http://craftcms.stackexchange.com/questions/16096/tasks-either-dont-start-or-dont-run-as-background-processes-on-valet-caddy-se/16097 

Given that Valet (and Caddy Server) are relatively new & gaining popularity, it _might_ bea fix that could be added to core by P&T (unless it has some negative unrealized implications).
