### ISSUE TITLE
Can't map or import fields

### ISSUE THREAD

**Issue by jeffakaufman** [boboldehampsink/import#128]
I am trying to import a csv into http://weelicious.kidevelopment.com/, but I can't see any way to map the fields here https://www.dropbox.com/s/kilm63np7xz61ve/Screenshot%202016-07-23%2011.17.15.png?dl=0. When I hit next I get the error below:

What am I doing wrong?

Internal Server Error

Argument 2 passed to Craft\BaseAssetSourceType::insertFileByPath() must be an instance of Craft\AssetFolderModel, null given, called in /home/forge/weelicious.kidevelopment.com/craft/plugins/import/controllers/ImportController.php on line 64

**Comment by boboldehampsink** [comment]
I'm guessing this has to do with #132
