### ISSUE TITLE
Stuck Task, Local Environment Only

### ISSUE THREAD

**Issue by smockensturm** [boboldehampsink/import#130]
What would cause an import to hang up and never finish? ( _tiny_ .csv, < 1k, 1 record ) Orange dot in the history, unfinished task at the bottom of the CP nav...

This only happens on the local dev environment (remote mySQL). We have to manually clear the task from the database in order to even try again.

Up on the server it works like a champ. (we've increased local env PHP max_execution_time to no avail.)

Thanks.

Craft 2.6.2903
Import 0.8.28

**Comment by smockensturm** [comment]
`'devMode' => false`

gets it working locally. painful to develop a plugin with hooks in that state, tho.

**Comment by boboldehampsink** [comment]
Looks like something you should contact Craft support with.

**Comment by johanneslamers** [comment]
Have exactly the same... devMode on false solved the problem

**Comment by smockensturm** [comment]
Not really a solution. The overhead in devMode is no joke. Here's what Brad at P&T says:

> devMode uses a lot more memory on a given PHP request and importing probably already requires significant memory, so my guess is that you're running into your php.ini file's memory_limit or max_execution_time limits or something similar.

Oh well. ¯\_(ツ)_/¯

**Comment by smockensturm** [comment]
We have increased memory_limit 10 fold (1280M)
We have increased max_execution_time 100 fold (30000)
We have increased max_input_time 100 fold (60000)

And STILL this Import plug-in hangs up in the first half a second when Craft devMode is set to true. What are we doing wrong? What else can we be looking for?

**Comment by boboldehampsink** [comment]
Do you use automatic task running? Do you use gzip? (maybe even unnoticed?). Do the logs say anything?

**Comment by smockensturm** [comment]
No automatic task running. No gzip. But now... version 0.8.32 (dev mode true) can't even get past this error:

Undefined index: assetsource

(We should be able to use this plug-in without having to define an asset source.) When we **_do_** define an asset source (albeit empty) we get this error:

https://github.com/boboldehampsink/import/issues/133

So that's one issue (or two).

Prior to installing 0.8.32, we did manage to isolate the hanging import (dev mode true) to the mere presence of a SmartMap field in the targeted section. SmartMap developer says "don't use import in dev mode". Well that's just nuts.

So, at the moment, I cannot even duplicate the original problem (hanging import) with your latest release.

**Comment by smockensturm** [comment]
Installed the development release, which appears to suppress the PHP asset errors. So now we're back to the hanging import. Again, traced to the presence of SmartMap.

But... the logs that we try to force here

https://github.com/boboldehampsink/import/issues/137

**_do_** get output when dev mode is true. Even though the import is unsuccessful.

I've zipped up and attached all logs here
[Archive.zip](https://github.com/boboldehampsink/import/files/471771/Archive.zip)

**Comment by boboldehampsink** [comment]
Ok, looks like a SmartMap issue then. File a bug report there.

**Comment by lindseydiloreto** [comment]
**RE: Smart Map...**

It's a super edge case, but it seems like there's a conflict with devMode, Import, and **geolocation**. To circumvent this conflict, simply disable geolocation while you run the import.

<img width="920" alt="Smart Map Settings" src="https://cloud.githubusercontent.com/assets/5309692/18566214/d7c551c0-7b47-11e6-9b29-0fc1dec5c77b.png">

I'll continue to investigate until this is fully resolved, but this workaround should be satisfactory in most situations.

**Comment by lindseydiloreto** [comment]
This has been fixed for the next release of Smart Map.
