### ISSUE TITLE
Plugin stuck in Generating Search Keywords loop.

### ISSUE THREAD

**Issue by ShaneHowell** [boboldehampsink/import#131]
Import was successful but it's stuck in a loop. 
Tried disabling and uninstalling the plugin but it still displays and won't go away.
CSV only has 50 items in it.

Craft CMS 2.6.2797
PHP Version 5.6.20-0+deb8u1

<img width="228" alt="screen shot 2016-08-06 at 4 37 34 pm" src="https://cloud.githubusercontent.com/assets/5295741/17458945/2868b720-5bf4-11e6-993d-94c9fa8efaed.png">

<img width="409" alt="screen shot 2016-08-06 at 3 59 34 pm" src="https://cloud.githubusercontent.com/assets/5295741/17458851/69ef1fc2-5bef-11e6-8391-78c31e6b1a84.png">

**Comment by ShaneHowell** [comment]
It would appear that the plugin doesn't like the [Neo plugin](https://github.com/benjamminf/craft-neo). There were a ton of pending tasks in the `craft_tasks` db table for Neo:

<img width="1377" alt="screen shot 2016-08-06 at 4 46 04 pm" src="https://cloud.githubusercontent.com/assets/5295741/17458991/7d2536b6-5bf5-11e6-8212-917ddf2943ac.png">

**Comment by benjamminf** [comment]
Yep this is likely a problem with where I chose to run the keywords task. This should be fixed in the next release.
