### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by lindseydiloreto** [boboldehampsink/import#139]
Getting a strange error message when I try to submit Step 1 of the import...

<img width="680" title="Step 1" src="https://cloud.githubusercontent.com/assets/5309692/18541558/c7908d14-7ada-11e6-9555-a27ee5d348f6.png">

---

I click "Next", and get this...

![Error](https://cloud.githubusercontent.com/assets/5309692/18541613/0f74cf0a-7adb-11e6-960a-e52fd0e82bc1.png)

---

Any thoughts? Let me know if you need more information.

**Comment by boboldehampsink** [comment]
This seems like a duplicate of #133, read my comment there and let me know what you find.

**Comment by lindseydiloreto** [comment]
Agreed, it's a duplicate. Closing this thread & following #133 instead.
