### ISSUE TITLE
Getting Error on import: Columns and data did not match, could be due to malformed CSV row.

### ISSUE THREAD

**Issue by keithmancuso** [boboldehampsink/import#14]
Tried to do a simple import and its getting CSV issues?  tried exporting from excel and from numbers on a mac.
Here it the file i used:
https://www.dropbox.com/s/cy53vuhfmje746l/testImport.csv?dl=0

any idea whats wrong?

**Comment by klick** [comment]
I keep getting this error as well and we could not establish a pattern, it’s on and off. Mostly it fails, deleting rows helps but as said, no real pattern. So we don’t know where to start. Is there a maximum count on columns? Our testtable sports 85 columns with 27 rows. Is that too much?

**Comment by boboldehampsink** [comment]
No, this shouldn't matter. Maybe there's something wrong with the escaping of columns?

**Comment by klick** [comment]
Interestingly, it was an malformed CSV. Occam's razor. :)
Thanks for the plugin! It’s a god send.

**Comment by boboldehampsink** [comment]
That's why the error message says it ;-) it is never wrong ;-)

**Comment by klick** [comment]
Just fyi: culprit were double identical columns. Just found out today.
