### ISSUE TITLE
Error importing users with old ID

### ISSUE THREAD

**Issue by tiborsaas** [boboldehampsink/import#140]
Hello,

I'm trying to import users keeping their old ID, but it doesn't seem to work. I picked the "append data" option on the main page. The import history looks green, but in the details it says it can't find the user with the given ID.

![image](https://cloud.githubusercontent.com/assets/342688/18951690/bd2f08a6-8646-11e6-833a-a9ae2a0ccee9.png)

It also updated my admin user with the id 1 and I was lucky that I was able to request a password reset :)

The reason I want to keep the old ID is because I need to match it with other imported tables.

**Comment by tiborsaas** [comment]
It seems it can't be done via the Craft API. I'd suggest if people import users in the "append" mode, then disable the ID option as a target attribute.

**Comment by boboldehampsink** [comment]
Ok, too bad. Thanks for trying.
