### ISSUE TITLE
Mapping parent entries and rich text

### ISSUE THREAD

**Issue by brianpaddling** [boboldehampsink/import#142]
I am trying to import record entries and trying to use the CraftID instead of the field title but not having success.  How do I import with the CraftID?

Also, how do I select Rich Text as the type of data being imported?
![image](https://cloud.githubusercontent.com/assets/22889552/19440664/b3a03ae0-9450-11e6-8a01-9e0c626ecea2.png)

![image](https://cloud.githubusercontent.com/assets/22889552/19440678/cb26256c-9450-11e6-83be-b1d4475e33fc.png)

I can send full data samples and give access to our dev server if needed.
At this point, I would prefer to just pay someone to import the data that understands it rather than continue trying to figure it out.

**Comment by boboldehampsink** [comment]
Hi Brian,

What do you mean by the CraftID? Is that just the ID of the entry? You can select that as import field.
Also, it looks like Content is a matrix field, isn't it? If so, is this something custom you wrote? Import doesn't support Matrix out-of-the-box.

**Comment by brianpaddling** [comment]
> What do you mean by the CraftID? Is that just the ID of the entry?
Yes, it is the ID of that entry.  I tried using it and it only worked for one entry and failed on the rest.

> Also, it looks like Content is a matrix field, isn't it? If so, is this something custom you wrote? Import doesn't support Matrix out-of-the-box.
I believe it is a matrix field so that could be the issue.

I am not a developer, I am the owner of the site that is being developed.  I honestly have no business working at this level but trying to get the project completed as our developer is swamped with other parts of the project.  I would much prefer to hand you two different CSV files and have the import completed.  Let me know if that is an option.
