### ISSUE TITLE
Plugin not recognized on install

### ISSUE THREAD

**Issue by romikadri** [boboldehampsink/import#143]
Hi there, excited to install but when I follow the normal plugin install procedure (upload contents of .zip to craft/plugins folder, then go to Settings/Plugins) the plugin does not display.  Same for 'export' plugin.

**Comment by romikadri** [comment]
Realized folder had "-develop" appended to it, so Craft wasn't recognizing.  Perhaps put a note on this in readme for inexperienced craft devs such as myself? :)  Thank you for the awesome plugin!

**Comment by boboldehampsink** [comment]
Actually this is in the readme:

Important:
The plugin's folder should be named "import"
