### ISSUE TITLE
Make use of dataProviders in unit tests

### ISSUE THREAD

**Issue by brammittendorff-dd** [boboldehampsink/import#166]
I see you are generating arrays to provide data, this can be done better in PHPUnit by a dataProvider:

https://phpunit.de/manual/current/en/writing-tests-for-phpunit.html#writing-tests-for-phpunit.data-providers

**Comment by boboldehampsink** [comment]
I already use dataproviders everywhere, did you find a place where it's not used and should?

**Comment by brammittendorff-dd** [comment]
Yes thats right thats why i think you might have missed a few in file:
https://github.com/boboldehampsink/import/blob/develop/tests/ImportServiceTest.php

You use ```$expectedData```, which as you describe is data:

``` $expectedData = array(
            array('row1value1', 'row1value2', 'row1value3', 'row1value4', 'row1value5'),
            array('row1value1', 'row2value2', 'row3value3', 'row4value4', 'row5value5'),
        );```

And ```$data```:
```
$data = array('settings1' => 'value1', 'settings2' => 'value2');
```

```
$data = array('settings1' => 'value1', 'settings2' => 'value2');
```

And you use a lot of arrays with variable name ```$settings``` i'm not quite sure if this is data or maybe should be private... But if it fits the requirements for the dataProvider then you can use it.

**Comment by boboldehampsink** [comment]
That's because that's the one expected result for that assertion. This has nothing to do with data providers.

**Comment by brammittendorff-dd** [comment]
So this isn't data you can provide?

**Comment by boboldehampsink** [comment]
You could, but we're only testing one outcome so that would be overhead.

**Comment by brammittendorff-dd** [comment]
And the ```$data``` is 2 times the same array?

**Comment by boboldehampsink** [comment]
Yes, that's the content of the mocked csv. Please read the code first.

**Comment by brammittendorff-dd** [comment]
Again this isn't data you can provide?

**Comment by boboldehampsink** [comment]
We're testing only one multidimensional array - its totally unneeded. Now stop wasting my time.

**Comment by brammittendorff-dd** [comment]
Looks a bit sloppy to me, but hey it is your code.
