### ISSUE TITLE
Importing users with useEmailAsUsername true?

### ISSUE THREAD

**Issue by samhibberd** [boboldehampsink/import#27]
It looks like importing new users throws a validation error for username when useEmailAsUsername is true?

**Comment by boboldehampsink** [comment]
Which error did you get?

**Comment by samhibberd** [comment]
Getting a 'Username is required' validation error in the history log.

**Comment by boboldehampsink** [comment]
Could you try the develop branch to see if this is fixed for you?

**Comment by samhibberd** [comment]
Hi,

I am out of the office on holiday returning Monday 2nd of February All emails will be dealt with on my return.

If you do have anything urgent please don’t hesitate to get in contact with Ben on 01962 809 103 or ben@fruitstudios.co.uk.

Thank you.

Kind regards,

Sam Hibberd
 
Fruit Studios Ltd
First Floor
100 High Street
Winchester
SO23 9AH
 
====================================================

This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify Fruit Studios Ltd immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. E-mail transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. Fruit Studios Ltd does not accept liability for any errors or omissions in the contents of this message, which arise as a result of e-mail transmission. Opinions expressed in this email are those of Sam Hibberd, and do not necessarily reflect those of Fruit Studios Ltd. If verification is required please request a hard-copy version.

====================================================

**Comment by samhibberd** [comment]
Perfect, fixed!

**Comment by boboldehampsink** [comment]
I have just released this bugfix, thanks for helping!
