### ISSUE TITLE
Possible to link to CSV file?

### ISSUE THREAD

**Issue by engram-design** [boboldehampsink/import#29]
Rather than uploading the CSV in a once-off scenario, I'm wanting to be able to point it to a URL that resolves to a CSV file which gets updated (via FTP) once a day.

Currently, I can only see the option to upload a CSV, rather the specify a URL. Would this be possible?

**Comment by boboldehampsink** [comment]
Hi Josh, I don't have such plans at this time. I'll write it down for the future.
