### ISSUE TITLE
Doesn't import both a parent and child category of the same category group

### ISSUE THREAD

**Issue by johnwbaxter** [boboldehampsink/import#32]
Hi, importing two categories from one category group where one of the categories is the child of the other doesn't seem to work. It only imports one of the categories. My category data is delimited with a comma like so: 

parent-category-url,child-category-url

**Comment by boboldehampsink** [comment]
That should work, are you sure the uri's are correct? It has to be the "uri", not the url

**Comment by johnwbaxter** [comment]
Ah, so you are saying i would need:

parent-category-url,parent-category-url/child-category-url

to make it pick up both?

**Comment by boboldehampsink** [comment]
Only the latter would be enough

**Comment by johnwbaxter** [comment]
Ah right, ok, thank you very much indeed! Fantastic plugin btw!

**Comment by boboldehampsink** [comment]
Did this solve your problem?

**Comment by johnwbaxter** [comment]
In the end, for the small amount of sub categories i had and the layout of the data i had, it was quicker to move the sub categories to the top level, import the data and then move the sub categories back to being sub categories again! That worked! :)

**Comment by johnwbaxter** [comment]
On a side note, any ideas on when this plugin might be supporting the assets fieldtype?

**Comment by boboldehampsink** [comment]
Great. It's on the list but I haven't had much time for it lately.

**Comment by johnwbaxter** [comment]
Ah ok, that's cool, it would certainly be a really useful addition! Such a great plugin though, thanks again!! :)
