### ISSUE TITLE
Error during install on Craft Personal

### ISSUE THREAD

**Issue by laverboy** [boboldehampsink/import#33]
During the install of the plugin I get the following error message:

    Internal Server Error
    Craft Client is required to perform this action.

When I return to the admin area, the plugin seems to have installed correctly, adding a new menu item 'Import'.

I have not yet checked whether everything is actually working or not. But I thought I would let you know.

**Comment by boboldehampsink** [comment]
Could you uninstall it and try the latest develop version? I just pushed a fix there.

**Comment by laverboy** [comment]
I have just pulled down the latest, and yes it seems to have fixed it.
Excellent!

**Comment by boboldehampsink** [comment]
I have just released it to public, thanks for helping
