### ISSUE TITLE
Import to Matrix Field

### ISSUE THREAD

**Issue by Sanity11** [boboldehampsink/import#37]
Hi Guys,

I'm working with your awesome plugin. I have a category containing a matrix field (one block type). The matrix field has a category and a text input field. Is it possible to import to matrix fields and category fields? Do you have an example of that?

Thanks!

**Comment by boboldehampsink** [comment]
There's currently no way to import Matrix fields. You can use any of the hooks (most likely modifyImportRow) to process Matrix data yourself (and if you find a good way, please submit a pull request). Categories are linked by refering to them as Headcategory/Subcategory/Subsubcategory if they're in a structure.
