### ISSUE TITLE
X is a required field

### ISSUE THREAD

**Issue by krazyjakee** [boboldehampsink/import#39]
I've been tearing my hair out, I just cannot see what I'm doing wrong.

You can download the CSV I am importing here: http://csvlint.io/validation/54f84a2f6373760234060000

Seems to import fine but when I look at the log... ![](http://i.imgur.com/CJkjoNc.png)

No new entries are created at all.

Why is this happening?

**Comment by krazyjakee** [comment]
%$@£(%$£()@U*%$B 38 530%$£@%

I hadn't created the associated entry.

Need some more feedback if an associated entry is not found.

**Comment by boboldehampsink** [comment]
This is how Craft returns the error, there's not much I can do.

**Comment by krazyjakee** [comment]
Ok no problem. Thanks so much for this plugin bob, it's an absolute lifesaver.
