### ISSUE TITLE
Support for categories

### ISSUE THREAD

**Issue by krazyjakee** [boboldehampsink/import#40]
An entry field, that is, a field where you associate entries worked fine by passing the title.
However, doing the same with a category fails and just gives me "X cannot be blank".

In case I am unclear, I have an entry where you can associate categories (Manufacturer). The importer cannot find a match on the manufacturer category even though it exists.

This time the category definitely exists, before I had the issue where it did not exist and threw this error (#39). Now there is now excuse other than categories are not supported yet.

In the readme it says
> "Will connect Entries (also Structures), **Categories**, Users and Assets by searching for them"

This is currently not working for me.

My CSV is correctly formatted (checked on csvlint).

**Comment by boboldehampsink** [comment]
I'm sorry, my documentation fails here. You have to specify categories like Headcategory/Subcategory/Subsubcategory (example) if they're in a structure.

**Comment by krazyjakee** [comment]
I will have a play when I next get the chance, thanks very much.

**Comment by krazyjakee** [comment]
"Manufacturer is a required field"

This is the most common error I encounter. There is something wrong here.

Here are my categories
![](http://i.imgur.com/7Q7RAUS.png)

Here is my CSV
```csv
"model","price","Manufacturer","condition","specsBerthSleeps","specsMtplm","specsMiro","specInternalLengthFeet","internalLengthInches","year"
"Challenger 520","7995","Swift","Used","4","1550","1345","17","9","2006"
```

Clearly the manufacturer is defined.
![](http://i.imgur.com/ToqwKVt.png)

The first entry imported never gives an error, even if there is one. I can only tell if there is an error by importing multiple items.

**Comment by boboldehampsink** [comment]
Is your manufacturer field set up to find "Swift" in the manufacturers pool? Try this for yourself. The first imported entry status might be a bug, I will look into it.

**Comment by krazyjakee** [comment]
Here is the data pointer to the manufacturer pool.
![](http://i.imgur.com/KTREXy4.png)

I also tried referencing the categories group "All Manufacturers/Swift" and it's handle "manufacturers/Swift" but to no avail.

**Comment by boboldehampsink** [comment]
What is the "url" you have set for manufacturers?

**Comment by krazyjakee** [comment]
The manufacturers categories don't have their own urls.

**Comment by boboldehampsink** [comment]
Ok, I should probably mention that so far there's no support for url-less categories. I will have to work on this :-)

**Comment by krazyjakee** [comment]
Woop! Thanks bro, now it's working! :dancers:

**Comment by boboldehampsink** [comment]
Nice. I have just fixed the log never showing the first errors. Will look into url-less category importing soon.
