### ISSUE TITLE
Import stalled...

### ISSUE THREAD

**Issue by sl8r** [boboldehampsink/import#41]
I have an issue where the import stalled and there is no way to kill the import. I uninstalled the plugin and reinstalled to no avail. I now have one stalled import and another one I setup that says pending. How can I rectify this so I can attempt another import? Thanks so much!

**Comment by sl8r** [comment]
Seems like this explains my issue which is not related to Import. http://buildwithcraft.com/help/stuck-tasks.

**Comment by boboldehampsink** [comment]
Good thing you found it.
