### ISSUE TITLE
No entries imported

### ISSUE THREAD

**Issue by rgbjay** [boboldehampsink/import#42]
I have installed the plugin and ran what looks like a successful import (no line errors, green indicator) but no new entries have been imported from a csv of 12 records of data.

I am not getting any errors so am having trouble debugging. I am a noob to Craft so I apologise if I have missed something fundamental but after a successful import I was expecting to see the new entries in my entries list under the particular entry type.

Any help appreciated!

J

**Comment by rgbjay** [comment]
I should also add that when choosing to append data the import always fails

**Comment by boboldehampsink** [comment]
Did you select a criterium that is unique? And what do you mean by "fails"? Does the Task circle get red?

**Comment by rgbjay** [comment]
Yes the circle appears red and the import fails if I choose to append the import.

If I choose to delete or replace it shows as successful (green circle) but no entries are imported.

How should I be using the criterium options?

**Comment by boboldehampsink** [comment]
If you run Craft in devMode and encounter the red circle, it should say something about this in the craft logs.
You should set a criterium field which is unique and identifies entries to be replaced.

**Comment by rgbjay** [comment]
Ideally I want to append the new data, rather than delete or replace.

I'm not sure I fully understand how the criterium fields work but as I'm looking to append rather than replace I'm not too concerned about that at this stage.

I've checked the Craft log files and can't see any errors being logged in them, and I am running in dev mode. Its as though its doing the import but not actually inserting the new data in the database.

Do the fields in the csv have to match the fields in the entry type exactly?

**Comment by rgbjay** [comment]
#43 appears to have fixed this issue, thanks for all the help
