### ISSUE TITLE
Imported date values not recognised until entry is re-saved

### ISSUE THREAD

**Issue by jstewartdesign** [boboldehampsink/import#47]
I have imported a series of entries but they don't appear in the front-end when filtering them by a date field. If I go into the entry and re-save they appear.

It is as though Craft is not registering the date until the page is saved.

Any thoughts? Thanks for the awesome plugin!

**Comment by boboldehampsink** [comment]
Do the dates correctly appear in the CP immediately?

**Comment by jstewartdesign** [comment]
Yes, when you load the entry in CP the dates are correct and then on save it appears on the site.

I imported using the format YYYY-MM-DD HH:MM:SS worked previously on another website.

We're using cache tag, but its disabled in our local environments and we've tried clearing the cache etc

**Comment by boboldehampsink** [comment]
What logics do you use for filtering by date?

**Comment by jstewartdesign** [comment]
{% set entries = entries.endDate( '< ' ~ now ) %}

Where endDate is the field we've imported into

**Comment by boboldehampsink** [comment]
Mmm that should be ok, is there any way you can make this reproducable?
