### ISSUE TITLE
Ability to automatically add assets to asset field.

### ISSUE THREAD

**Issue by krazyjakee** [boboldehampsink/import#48]
Using this fantastic plugin I managed to import hundreds of pages. The last thing I was not able to do automatically was add the image assets to a gallery. This had to be done manually.

I wrote a script to export from the previous site and download all images, creating a folder in craft assets with the correct slug. I then re-indexed the assets and the images were associated with the entry, but not added to the asset field. So for each entry I had to click add asset, select all and save. Painful.

Is there any way this could be done through a new feature in import?

**Comment by boboldehampsink** [comment]
Well, as long as they are indexed and THEN you run import, this will work.

**Comment by krazyjakee** [comment]
How can it work when there is no option of which field to import associated assets?

**Comment by boboldehampsink** [comment]
What do you mean? You can map to your assets field just fine?

**Comment by krazyjakee** [comment]
How?

**Comment by krazyjakee** [comment]
I think  an example CSV in the readme would go a long way to explaining things, especially the functionality that is not documented such as categories and multiple items (arrays).

**Comment by boboldehampsink** [comment]
There's a FAQ in the README that I added last week, this explains both your questions

**Comment by krazyjakee** [comment]
ok i'll test assets today.
