### ISSUE TITLE
`modifyImportRow` hook

### ISSUE THREAD

**Issue by steverowling** [boboldehampsink/import#51]
Should the `modifyImportRow` hook use referenced variables for `&$entry`, `&$settings['map']` and `&$data` to allow the called function to alter the values in the row before the new entry is imported in the same way that the `registerImportOperation` hook does for the `&$data` variable?

**Comment by boboldehampsink** [comment]
Now available in the develop branch.

**Comment by steverowling** [comment]
On further investigation, it appears that I was wrong about this and the reference sign should now only be included on function definitions. See the [PHP manual](http://php.net/manual/en/language.references.pass.php) for details. My apologies!

**Comment by boboldehampsink** [comment]
I'll have to test this. At least its clear now that you can pass it by reference.

**Comment by boboldehampsink** [comment]
This caused issues, issue closed.
