### ISSUE TITLE
User import and registration emails

### ISSUE THREAD

**Issue by timkelty** [boboldehampsink/import#53]
I'm wondering what happens by design with the registration emails when I import a bunch of users with this?

Ideally, I need to import users _and_ send registration emails.

**Comment by boboldehampsink** [comment]
You can set this at user settings right?

**Comment by timkelty** [comment]
You mean per-user?

I could go into each imported user and click "Send password reset email", but that's what I'm trying to avoid, as I'm importing hundreds of users.

I would also rather users got the "activation" email and not the password reset email.

**Comment by boboldehampsink** [comment]
Ah you want to set this per user?

**Comment by timkelty** [comment]
I want each user to get an activation email, yes.

**Comment by boboldehampsink** [comment]
But not control this per user - you just want one setting so they all get it.

**Comment by timkelty** [comment]
Right.

Maybe an "import as pending/send activation email" setting would make sense?
When you create a user in Craft, it defaults to pending, but Import sets them as active.

**Comment by boboldehampsink** [comment]
I don't think so - you can use this setting? ![screen shot 2015-04-23 at 08 53 05](https://cloud.githubusercontent.com/assets/378974/7291876/2fa32a9c-e996-11e4-8b34-9adbc7431c99.png)

**Comment by timkelty** [comment]
You're right - that setting controls if they get imported as pending/active.
I don't think *Import* respects this value, though. Users are always imported as active.

So, my original question/feature request remains: how would I send registration emails to imported users.

Thanks!

**Comment by boboldehampsink** [comment]
I don't really get it. I've just tested this, and while importing a whole bunch of registration emails came in...

**Comment by timkelty** [comment]
Weird! Ok, let me run some more tests.
What setting was the "Verify email addresses?" in when you tested?

**Comment by boboldehampsink** [comment]
It was on

**Comment by timkelty** [comment]
Ok. Thanks a bunch for testing.
I'll try it again today and see what happens.

**Comment by boboldehampsink** [comment]
Did you get any new results?

**Comment by timkelty** [comment]
Hey - so sorry, got slammed with work. I'll let you know as soon as I test.

**Comment by luwes** [comment]
At my end all users get imported as **active** by default also. Is there a way to put them in **pending** and also send the activation email?

**Comment by migswd** [comment]
Hey Luwes. Would you share you csv file and the version of import plugin you are using because we cannot make it work and we have no errors here !

**Comment by migswd** [comment]
For me checked the "Verify email addresses?" option but I receive no emails on import.

**Comment by boboldehampsink** [comment]
You should be able to use an extra field called "Status", and just set it to "pending" there.

**Comment by luwes** [comment]
Thanks for the reply. I ended up adding a line of code for that in Import_UserService, `$element->pending = true;`

**Comment by boboldehampsink** [comment]
Thanks @luwes, i've added that for the next release
