### ISSUE TITLE
Setting related entries

### ISSUE THREAD

**Issue by klick** [boboldehampsink/import#54]
Is it possible to set a related entry?

For example, I have an entry **“Sun”** in another section and in my CSV for importing entries there is a column filled with **“Sun”** values. Right now simply mapping does not seem to pick **“Sun”** as a related entry. 

Is there anything special to it which i am missing? The Readme suggests, that this is possible (_“Will connect Entries (…)”_).

**Comment by boboldehampsink** [comment]
Sure, just mention the title of the entry you want to connect to.

**Comment by klick** [comment]
This is how I thought it was working but no luck.

**Comment by klick** [comment]
Got it. Forgot to check the other locales.
