### ISSUE TITLE
Group option checkboxes for a User import are disabled

### ISSUE THREAD

**Issue by l3ftblank** [boboldehampsink/import#56]
I've installed 0.8.22 on a Craft Pro 2.3.2644 installation, and when I'm setting up a User import, the checkboxes for the Group selection are all disabled. I'm looking to only add users to one of the two groups I have set up.

Also, the Type dropdown only contains 'Users'. As I'm only trying to do a User import this is okay in this case, but shouldn't it also contain other Types?

The backup database checkbox is also disabled.

When I try to actually run the import with a CSV file, I get a Template Error - screenshots included.

![ss1](https://cloud.githubusercontent.com/assets/874374/7516624/8209860e-f4c8-11e4-83a2-3005fdf728aa.jpg)
![ss2](https://cloud.githubusercontent.com/assets/874374/7516628/84db5ede-f4c8-11e4-8513-4f223e03d52f.jpg)
![ss3](https://cloud.githubusercontent.com/assets/874374/7516800/6fded6b8-f4c9-11e4-8b12-2f8af6e7368e.jpg)

**Comment by boboldehampsink** [comment]
Found it! The javascript was only being executed when you have entries. I've fixed this in the latest develop branch and about to release it.
