### ISSUE TITLE
How to format a CSV to work with Structure hierarchy 

### ISSUE THREAD

**Issue by joshuapease** [boboldehampsink/import#57]
Hello! I've been testing out the import plugin to see how it works with structure entries. 

I'm not totally clear on how to write my CSV files so they will properly nest parent and child entries in a structure. 

Questions: 
**Q:** How should I write my CSVs so parent & child entries work properly?

**Q:** Do parent entries already need to exist before I import a CSV? Or can they be created form the came CSV import as their child entries?

**Comment by boboldehampsink** [comment]
Write it like Ancestor/Child/Entry and connect as "Ancestor". The entry should exist, but if it comes in the row before then it will exist and it will pass.

**Comment by joshuapease** [comment]
Hmm, I'm still having trouble achieving the structure I'm going for. 

[Here's a screenshot of what I'd like to achieve](https://www.dropbox.com/s/aj213pw8qvmha4a/Screenshot%202015-05-25%2014.45.24.png?dl=0)

[Here's a screenshot of my CSV file](https://www.dropbox.com/s/u66uekn1c49wc17/Screenshot%202015-05-25%2014.46.39.png?dl=0). 

What am I doing wrong?

**Comment by boboldehampsink** [comment]
That should be ok! I'll look into it

**Comment by joshuapease** [comment]
Actually! I got it working. 

Probably just mistakes on my end from working too late at night. Your plugin rocks!

**Comment by boboldehampsink** [comment]
Awesome, I'll leave this issue open because I will have to document this

**Comment by joshuapease** [comment]
Ahh, I just realized that I needed to check **Entries in this section have their own URLs** in order for section nesting to work. 

Might be a good thing to include in the documentation too.
