### ISSUE TITLE
Error message when trying to import large csv file.

### ISSUE THREAD

**Issue by lettie16** [boboldehampsink/import#58]
I am trying to use this plugin to import a csv which is just under 7mb but it is throwing the following error:

Fatal error: Out of memory (allocated 34078720) (tried to allocate 107 bytes) in crafttest/craft/plugins/import/services/ImportService.php on line 725

Any ideas on how to fix this?

**Comment by boboldehampsink** [comment]
Increase your memory limit

**Comment by lettie16** [comment]
What is the file limit for this. Just tried a reduced user file which is only 2.8mb?

**Comment by boboldehampsink** [comment]
This is up to you, you can control this in your server settings

**Comment by lettie16** [comment]
Hmmm can I do this via craft or add somerthing into your plugin. Don't have access to php.ini on shared server?

**Comment by boboldehampsink** [comment]
I'll look into it. The easiest way for now is to split up the csv into multiple smaller files.

**Comment by lettie16** [comment]
Yeah. The thing is I am trying to import legacy users into a new database. 13000 of them. So not sure what tables need to be imported in relation to the craft_users table. If I just drop and replace the craft_user table using sql they don't show up in the CMS. I'm guessing because I need the element table entries as well. Not sure about any others tables though. We only want to keep the basic info in the craft_users table and not worried about anything else as the site is being completely revamped so any existing user content or user groups are not required.

**Comment by lindseydiloreto** [comment]
Hey @lettie16, you might be able to bump up your PHP limits temporarily with this plugin...

>https://github.com/lindseydiloreto/craft-phptweak

My apologies if it's a little clunky... I wrote that a very long time ago. If you hit any snags, let me know!

If I'm too late to the party, and you've already sorted this out, then simply ignore me. :)

**Comment by boboldehampsink** [comment]
Did you sort it out @lettie16 ?

**Comment by lettie16** [comment]
@boboldehampsink Yes sorted it in the end but had to split the file so wasn't ideal but it solved the problem. Cheers
