### ISSUE TITLE
Users not importing but history shows no errors

### ISSUE THREAD

**Issue by russback** [boboldehampsink/import#60]
I have tried having validation on and off but get no errors from any of the lines in my CSV file.

I just don't get any users after the import has run at all.

I've tried an import with just Email only as that's the only required field but still no luck.

This is on Craft 2.4.

Any suggestions?

**Comment by amityweb** [comment]
Same for me.

**Comment by migswd** [comment]
Same for me. Does not work !

**Comment by boboldehampsink** [comment]
@russback @amityweb did you also use the password field?

**Comment by migswd** [comment]
================
UPDATE
In fact after reviewing my csv I made it work with password : I presume it was a duplicate headercolumn title.
My main problem still is a problem with french accents that are not supported by the plugin in al fields.
Otherwise  great plugin bravo :)

**Comment by boboldehampsink** [comment]
Closing this issue, then

**Comment by amityweb** [comment]
Can you let us know how this issue was fixed? As stated, I get no errors, so to me this issue is not fixed. If I made a mistake (e.g. this password field mentioned) then I would like to see the errors so I can rectify.

**Comment by boboldehampsink** [comment]
People got it to work. If you can't, can you send me a failing example CSV so I can try to reproduce it?

**Comment by amityweb** [comment]
I thought they got the import to work. But is the history showing errors now if the import didnt? If that worked, I may not need to troubleshoot or send you the CSV as I could see what the import error was and fix it.

**Comment by russback** [comment]
@boboldehampsink I moved on at the time but have just tried a new project and got the same issue.

Here's what I'm importing and what I have in the import settings.

I've tried with and without password but I do need to import the password. Doctor ID is a custom number field, no other custom fields are set up.

![image](https://cloud.githubusercontent.com/assets/2589006/18921370/6a7ead8c-859c-11e6-8e90-da3370bb9ce4.png)

![screen shot 2016-09-28 at 16 56 38](https://cloud.githubusercontent.com/assets/2589006/18921402/8c202f74-859c-11e6-95eb-60a7f63e3298.png)

**Comment by russback** [comment]
OK so it seems to be when I choose Replace data or Delete data that this occurs.

My assumption was that when an import runs, and existing users are found, they should be updated or deleted and then added. And if on that run there are new users, they should be created.

However it seems that's not happening. So perhaps the explanation of the import behaviour isn't clear enough?
