### ISSUE TITLE
Import is not picking up the correct category group from the dropdown 

### ISSUE THREAD

**Issue by johnwbaxter** [boboldehampsink/import#61]
When you choose a category group to import into, you are not selecting that specific category groups fields, you are just selecting the fields from the first category group in the CMS.

To replicate, create 2 category groups and only add fields to the second category group. Then, try and import data and choose the second category group as the one to import into. You will see that you do not have any fields in the field mapping dropdown.

**Comment by boboldehampsink** [comment]
I've added this to the develop branch, could you test it?

**Comment by boboldehampsink** [comment]
Released in 0.8.27
