### ISSUE TITLE
Asset support

### ISSUE THREAD

**Issue by outhouse** [boboldehampsink/import#63]
This plugin as saved my team days of migration time on a current project, thank you for it. 

I am wondering how hard it would be to add support for Assets? I'm migrating a large asset library at the moment (~500 assets) that all need captions and other meta data. I was able to pull them all into craft by doing a download + asset index rebuild, but manually restoring captions and other data is mind numbing. 

We could potentially fund development on this if that's helpful.

**Comment by boboldehampsink** [comment]
I'm planning this for a future release. In the meantime: the plugin is currently designed in a way so that you can easily hook in your own asset import service.

**Comment by boboldehampsink** [comment]
I've added this as part of issue #81 to the roadmap.
