### ISSUE TITLE
Unable to use ID as Criterium for finding existing data.

### ISSUE THREAD

**Issue by br-designer** [boboldehampsink/import#65]
Since ID's are unique and included with exports from your export plugin, it would be nice to be able to use ID as criterium for finding existing data. Do you have plans to include this?

**Comment by boboldehampsink** [comment]
Why are you unable? This should just work

**Comment by br-designer** [comment]
The field name dropdown down does not have an option to choose ID. So running the import with the ID as the Criterium does not work. See attached image to see what shows up in the dropdown.

I'm using the newest version of import and craft is updated.

![screen shot 2015-09-04 at 10 34 13 am](https://cloud.githubusercontent.com/assets/5600724/9687898/9c4278d2-52f1-11e5-9beb-bc8b93890ec5.png)

**Comment by boboldehampsink** [comment]
I've added this to the develop branch, would you test it?

**Comment by br-designer** [comment]
Definitely!

**Comment by boboldehampsink** [comment]
Did this work for you?

**Comment by br-designer** [comment]
Hey Bob, 

It worked! Thanks for looking into this.
