### ISSUE TITLE
This filetype is not valid: "text/x-comma-separated-values"

### ISSUE THREAD

**Issue by MrMarkCollins** [boboldehampsink/import#67]
Hello – I get this error message on the first screen (attach csv file etc.) when hitting 'Next':

This filetype is not valid: "text/x-comma-separated-values"

It's a fresh install of Craft (Craft Personal 2.4.2691) on localhost. I've reinstalled the plugin twice. I have also tried creating a new csv file with a couple of test words, just in case something was wrong with the actual csv file I need uploading.

I've searched previous issues but nothing noted. I'm at a loss. Any ideas please? Many thanks.

![2](https://cloud.githubusercontent.com/assets/1199275/9743093/5f0c2d3c-565c-11e5-9fa5-9d1336c8080d.png)
![1](https://cloud.githubusercontent.com/assets/1199275/9743094/5f159728-565c-11e5-8bd3-8906bf38098c.png)

**Comment by MrMarkCollins** [comment]
Thought I would try one last thing; a different browser. It works in Chrome (Mac) but it doesn't in Firefox (Mac).

**Comment by boboldehampsink** [comment]
text/x-comma-separated-values was not recognized yet, I'm adding this to the latest release
