### ISSUE TITLE
Import does not support french accents

### ISSUE THREAD

**Issue by migswd** [boboldehampsink/import#74]
The french accents é à ê etc are not well supported : it breaks the fields values and the passwords do not work.

**Comment by Hepburni** [comment]
Same with Swedish åäö, would be amazing if this could work. I guess it's essentially multi-byte string support we are looking for.

**Comment by boboldehampsink** [comment]
I think this depends on the further configuration of your Craft installation. Please read this paper and see if implementing this fixes your problems: http://static.zend.com/topics/multibyte-fgetcsv.pdf

**Comment by boboldehampsink** [comment]
Did the article help you guys with this?

**Comment by etheya** [comment]
Ah didn't see this I've just posted the same issue with the french language...  will have a look at the document

**Comment by etheya** [comment]
Not sure how I'm supposed to use that document posted.... any direction to test this would be appreciated.

**Comment by boboldehampsink** [comment]
Set the mb and locale settings on top of your index.php

**Comment by etheya** [comment]
Thanks Bob… will try that…

**Comment by boboldehampsink** [comment]
Did this work for you?

**Comment by boboldehampsink** [comment]
It worked at #87, closing this
