### ISSUE TITLE
Importing categories

### ISSUE THREAD

**Issue by joomkit** [boboldehampsink/import#76]
I have been trying to import nested categories like Countries and cities.

Have been through nearly all permutations. Here is a sample copy of my file:

Title,Slug,Parent,Ancestors
Antwerp,antwerp,,Belgium
Ghent,ghent,,Belgium
Zeebrugge,zeebrugge,,Belgium

They either don't get imported or go in flat, un-nested. 

An example import file for nested categories would be very useful but can you advide on how a large amount of nested categories can be imported?

**Comment by boboldehampsink** [comment]
Use "Ancestors" only and read the [FAQ](https://github.com/boboldehampsink/import#frequently-asked-questions)

**Comment by joomkit** [comment]
I had a bug in my config - all worked ok now.

However I notice that when i try and open and save a category i get a an error for the imported category as opposed to manually created in CP.
craft/app/services/CategoriesService.php(1045)
```
1033 
1034         // Is it set to be under a parent now, but didn't have one before?
1035         if ($category->newParentId !== '' && $category->level == 1)
1036         {
1037             return true;
1038         }
1039 
1040         // Is the newParentId set to a different category ID than its previous parent?
1041         $criteria = craft()->elements->getCriteria(ElementType::Category);
1042         $criteria->ancestorOf = $category;
1043         $criteria->ancestorDist = 1;
1044         $criteria->status = null;
1045         $criteria->locale = $entry->locale;
1046         $criteria->localeEnabled = null;
1047 
1048         $oldParent = $criteria->first();
1049         $oldParentId = ($oldParent ? $oldParent->id : '');
1050 
1051         if ($category->newParentId != $oldParentId)
1052         {
1053             return true;
1054         }
1055 
1056         // Must be set to the same one then
1057         return false;
```
I guess this is a locale thing? I see the dev branch supports locale but i couldnt et a successful import using the dev branch.

**Comment by boboldehampsink** [comment]
Hi, this seems to be a bug in Craft. I've reported the bug to Craft, lets hope it gets fixed soon!
