### ISSUE TITLE
Broken redirect after import

### ISSUE THREAD

**Issue by timkelty** [boboldehampsink/import#78]
When an import completes, I get redirected to `/admin/import/history/history/`

**Comment by boboldehampsink** [comment]
I've added a fix for this in the develop branch, care to test it?

**Comment by timkelty** [comment]
Hmmm still happening for me on the `develop` branch.

**Comment by boboldehampsink** [comment]
Very weird, I'm not able to reproduce it, and it has not happened before either. Can you debug it on your end perhaps?

**Comment by timkelty** [comment]
Yep, will do. Yeah looked at the code for the redirect, looks fine to me.

**Comment by boboldehampsink** [comment]
Did you find anything?

**Comment by timkelty** [comment]
Haven't had a chance - I'll try and check it out today.

Seems like a familiar problem (with another plugin)...maybe theres a certain config that triggers this behavior.

**Comment by timkelty** [comment]
No wonder I couldn't find it, it was a JS redirect!
