### ISSUE TITLE
Foreign characters not working on import...

### ISSUE THREAD

**Issue by etheya** [boboldehampsink/import#87]
Ive been using this to import a CSV file that has a 2nd locale which is FRENCH.... although its working I've noticed that there is an issue with the foreign characters in the french language..

It has no problem with ' in the sentence but if you import for example:  "Un bon bain pour être propre"

It only imports "Un bon bain pour "

It doesn't seem to like the foreign "ê" so therefore doesn't actually put the whole value into Craft.

Is there any way around this on import?

**Comment by etheya** [comment]
I noticed this post on another issue... but don't see how or where to implement this .... http://static.zend.com/topics/multibyte-fgetcsv.pdf

Can i just drop the line in the general.php file?

**Comment by etheya** [comment]
Will have a look… haven’t got around to testing it yet either way...

**Comment by boboldehampsink** [comment]
Did this work for you?

**Comment by etheya** [comment]
Hi Bob,

Yes it did if i remember correctly…. sorry was quite some time ago now.


Kind Regards

Brian Coult
Mobile Consultant | Designer | ExpressionEngine Developer
Etheya Digital Creativity Ltd

t. 07463 240076
e. brian@etheya-digitalcreativity.com <mailto:brian@etheya-digitalcreativity.com>
w. www.etheya-digitalcreativity.com <http://www.etheya-digitalcreativity.com/>

Skype: etheya-bc
LinkedIn: http://www.linkedin.com/pub/brian-coult/3/902/127 <http://www.linkedin.com/pub/brian-coult/3/902/127>
