### ISSUE TITLE
Error - [php] Only variables should be passed by reference 

### ISSUE THREAD

**Issue by ianshea** [boboldehampsink/import#96]
Received this error when trying to import a few things today. More specifically - the error was listed as:

`[error] [application] Encountered an error running task 8 (Import), step 1 of 3: Only variables should be passed by reference on line 151 of /site/craft/plugins/import/services/Import_HistoryService.php`

I'm running a local development environment via MAMP using PHP 7.

**Comment by irock195** [comment]
I'm really not a php guru by any means... but it looks like this issue relates to some [changes in PHP7](http://php.net/manual/en/migration70.incompatible.php).
