### ISSUE TITLE
Does importing a structure require that "Entries in this section have their own URLs" be checked?

### ISSUE THREAD

**Issue by joshuapease** [boboldehampsink/import#98]
Whenever I use this plugin to import into a Structure and want the Ancestors to be correct, I always have to enable "Entries in this section have their own URLs". 

Is this a limitation in Craft? Or am I not setting up my CSVs to import Ancestors properly? 

Many times in my projects I don't want my structures to use templates or have unique URLs. 

Love the plugin! Thanks

**Comment by boboldehampsink** [comment]
Hi, yes this has been a limitation I haven't been able to work around any other way.
