### ISSUE TITLE
Import doesn't seem to like escaped characters

### ISSUE THREAD

**Issue by lexbi** [boboldehampsink/import#99]
Import doesn't seem to like escaped characters, how can I import data like that? I'm on Craft 2.5

    "post_date","title","body"
    "2015-02-11 09:16:51","New Website","Welcome to our new <a href=\"http://www.website.com\">website</a>!"

When imported will return

    Welcome to our new <a href="%5C">website</a>!

Other attributes 

    alt=\"IMG_5952.JPG\"

Can return:

    alt="\&quot;IMG_5952.JPG\&quot;"

**Comment by lexbi** [comment]
Ok looks like I've managed to import my data ok now, though needed to replace all my escaped double quotes in my csv by adding more quotes around them... 

So had to replace all instances of `\"` with `""`. Would still be nice to select an escaped character in your plugin I guess, but this is fine for now!

**Comment by boboldehampsink** [comment]
Hi, escaping with double quotes is default CSV behavior :-)

**Comment by lexbi** [comment]
Hi, it would be nice if your plugin or it's docs suggested that's all it supports, took some time to figure that out. 

The data that I had was exported using sequel pro which by default escapes double quotes with a "\" character. It is not an uncommon way of escaping characters.
